### ISSUE TITLE
BUG: VCs are currently unavailable

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/virtual-contributor-engine-expert#47]
**Describe the bug**

**To Reproduce**

1. Go to https://alkem.io/myspaceevgeni/challenges/music
2. Mention the VC "Music" - it constantly responds with: "the Alkemio's VirtualContributor is currently unavailable."
<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4da16f6dadc8d32febc35e5b277ea1f7c0e5d29b/image.png" alt="image.png" />

**Expected behavior**
VCs respond.

**Comment by valentinyanakiev** [comment]
We deployed a fix on the ingestion service + reingested // verified a couple of VCs
